export const playListActionTypes = {
  GET_FEATURED_PLAYLIST: "GET_FEATURED_PLAYLIST",
  SELECT_PLAYLIST: "SELECT_PLAYLIST",
  SET_LOCAL_PLAYLIST: "SET_LOCAL_PLAYLIST",
  UPDATE_FEATURED_PLAYLIST: "UPDATE_FEATURED_PLAYLIST",
};
